package Java_Exception;

import java.util.Scanner;

public class MyCalculaor 
{
	long power (int n, int p) throws Exception{
		if (n < 0 || p < 0)
		{
			throw new Exception("n or p sghould not be negative.");
		} else if (n == 0 && p == 0)
		{
			throw new Exception("n and p should not be zero.");
		} else {
			return (long) Math.pow(n, p);
		}
	}
}

class Solution 
{
	public static void main(String[] args) 
	{
		Scanner in = new Scanner(System.in);
		while (in .hasNext())
		{
			int n = in.nextInt();
			int p = in.nextInt();
			MyCalculaor my_Calculaor = new MyCalculaor();
			try {
				System.out.println(my_Calculaor.power(n, p));
			} catch (Exception e) {
				System.out.println(e);
			}
		}
	}
}
